/**
 * The lesson format.
 *
 * A lesson is a deck of cards, each one a single interaction that takes ten
 * to forty seconds. There is no prose page followed by a quiz; the reading is
 * a card, the question is a card, the slider is a card. This is the shape
 * Brilliant and Duolingo converged on and the shape the old Module Reader
 * did not have.
 *
 * Content is authored as plain objects in this folder and validated by the
 * Zod schema below when the tracks are first loaded, so a typo in a lesson
 * fails loudly in development rather than rendering a broken card in the
 * field. Nothing in a card is generated by the model: every number is either
 * written here with its source or computed by utils/moneyMath.ts at render.
 */
import { z } from 'zod';

const base = { id: z.string().min(1) };

export const InfoCardSchema = z.object({
    ...base,
    type: z.literal('info'),
    title: z.string(),
    body: z.string(),
    /** One big figure with a caption, for the cards that turn on a number. */
    stat: z.object({ value: z.string(), label: z.string() }).optional(),
    source: z.string().optional(),
});

export const ChoiceCardSchema = z.object({
    ...base,
    type: z.literal('choice'),
    prompt: z.string(),
    options: z.array(z.string()).min(2).max(4),
    answer: z.number().int().min(0),
    explain: z.string(),
});

export const TrueFalseCardSchema = z.object({
    ...base,
    type: z.literal('trueFalse'),
    statement: z.string(),
    answer: z.boolean(),
    explain: z.string(),
});

export const EstimateCardSchema = z.object({
    ...base,
    type: z.literal('estimate'),
    prompt: z.string(),
    unit: z.enum(['inr', 'percent', 'months']),
    min: z.number(),
    max: z.number(),
    step: z.number().positive(),
    answer: z.number(),
    /** Fraction of the answer the guess may miss by and still count. */
    tolerance: z.number().min(0).max(1),
    explain: z.string(),
});

export const TapSortCardSchema = z.object({
    ...base,
    type: z.literal('tapSort'),
    prompt: z.string(),
    buckets: z.tuple([z.string(), z.string()]),
    items: z.array(z.object({ label: z.string(), bucket: z.union([z.literal(0), z.literal(1)]) })).min(3).max(8),
    explain: z.string(),
});

export const OrderStepsCardSchema = z.object({
    ...base,
    type: z.literal('orderSteps'),
    prompt: z.string(),
    /** In the correct order. The card shuffles them for display. */
    steps: z.array(z.string()).min(3).max(6),
    explain: z.string(),
});

export const SpotTrapCardSchema = z.object({
    ...base,
    type: z.literal('spotTrap'),
    prompt: z.string(),
    /** Rendered like a statement or slip. One of them is the trap. */
    lines: z.array(z.object({ label: z.string(), value: z.string().optional() })).min(3).max(8),
    trap: z.number().int().min(0),
    explain: z.string(),
});

export const ExplorableIdSchema = z.enum([
    'minimumDue', 'salarySlip', 'regimeCompare', 'runway', 'noCostEmi', 'cibil', 'inflation',
]);

export const ExplorableCardSchema = z.object({
    ...base,
    type: z.literal('explorable'),
    explorable: ExplorableIdSchema,
    prompt: z.string(),
    /** A question about what they just saw. Optional: some explorables are just for looking. */
    question: z.object({
        prompt: z.string(),
        options: z.array(z.string()).min(2).max(4),
        answer: z.number().int().min(0),
        explain: z.string(),
    }).optional(),
});

export const CardSchema = z.discriminatedUnion('type', [
    InfoCardSchema, ChoiceCardSchema, TrueFalseCardSchema, EstimateCardSchema, TapSortCardSchema,
    OrderStepsCardSchema, SpotTrapCardSchema, ExplorableCardSchema,
]);

export const LessonSchema = z.object({
    id: z.string().min(1),
    title: z.string(),
    summary: z.string(),
    minutes: z.number().int().positive(),
    cards: z.array(CardSchema).min(3),
});

export const TrackSchema = z.object({
    id: z.string().min(1),
    title: z.string(),
    description: z.string(),
    /** Who this is for, in one line, shown on the track card. */
    audience: z.string(),
    lessons: z.array(LessonSchema).min(1),
});

export type InfoCard = z.infer<typeof InfoCardSchema>;
export type ChoiceCard = z.infer<typeof ChoiceCardSchema>;
export type TrueFalseCard = z.infer<typeof TrueFalseCardSchema>;
export type EstimateCard = z.infer<typeof EstimateCardSchema>;
export type TapSortCard = z.infer<typeof TapSortCardSchema>;
export type OrderStepsCard = z.infer<typeof OrderStepsCardSchema>;
export type SpotTrapCard = z.infer<typeof SpotTrapCardSchema>;
export type ExplorableCard = z.infer<typeof ExplorableCardSchema>;
export type ExplorableId = z.infer<typeof ExplorableIdSchema>;
export type Card = z.infer<typeof CardSchema>;
export type Lesson = z.infer<typeof LessonSchema>;
export type Track = z.infer<typeof TrackSchema>;

/** Cards that have a right answer and therefore feed the mistake bank. */
export function isScorable(card: Card): boolean {
    if (card.type === 'info') return false;
    if (card.type === 'explorable') return Boolean(card.question);
    return true;
}

/**
 * Validate a track and check that every card id is unique across the whole
 * track, since card ids key the mistake bank. Throws in development; in a
 * release build the content has already been validated once, so this is a
 * belt over braces.
 */
export function validateTracks(tracks: Track[]): Track[] {
    const seen = new Set<string>();
    for (const t of tracks) {
        TrackSchema.parse(t);
        for (const l of t.lessons) {
            for (const c of l.cards) {
                const key = `${l.id}:${c.id}`;
                if (seen.has(key)) throw new Error(`Duplicate card id ${key}`);
                seen.add(key);
                if (c.type === 'choice' && c.answer >= c.options.length) throw new Error(`Bad answer index in ${key}`);
                if (c.type === 'spotTrap' && c.trap >= c.lines.length) throw new Error(`Bad trap index in ${key}`);
                if (c.type === 'explorable' && c.question && c.question.answer >= c.question.options.length) {
                    throw new Error(`Bad answer index in ${key}`);
                }
            }
        }
    }
    return tracks;
}
